"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { type Me, type MyEnrollment, getMe, getMyEnrollments } from "@/lib/api";

export default function EnrollmentVerificationPage() {
  const [me, setMe] = useState<Me | null>(null);
  const [enr, setEnr] = useState<MyEnrollment[]>([]);

  useEffect(() => {
    Promise.all([getMe(), getMyEnrollments()]).then(([m, e]) => { setMe(m); setEnr(e); }).catch(() => {});
  }, []);

  const credits = enr.reduce((s, e) => s + e.credits, 0);
  const term = enr[0]?.term ?? "the current term";

  return (
    <>
      <style>{`@media print { .no-print { display: none !important; } .doc-sheet { box-shadow: none !important; border: none !important; } body { background: #fff !important; } }`}</style>

      <div className="no-print" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
        <Link href="/student/documents" className="eyebrow">← Documents</Link>
        <span style={{ flex: 1 }} />
        <button className="primary" onClick={() => window.print()}>Print / Save as PDF</button>
      </div>

      <div className="doc-sheet card" style={{ maxWidth: 820, margin: "0 auto", padding: 40 }}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "2px solid var(--daust-navy)", paddingBottom: 16 }}>
          <div>
            <div style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 26, color: "var(--daust-navy)", letterSpacing: ".04em" }}>DAUST</div>
            <div className="muted" style={{ fontSize: 12 }}>Dakar American University of Science & Technology</div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 18 }}>Enrollment Verification</div>
            <div className="muted" style={{ fontSize: 12 }}>Issued {new Date().toLocaleDateString()}</div>
          </div>
        </div>

        <p style={{ margin: "20px 0", lineHeight: 1.6 }}>
          This certifies that <strong>{me?.name ?? "the student"}</strong> ({me?.email}) is enrolled at DAUST for{" "}
          <strong>{term}</strong>, carrying <strong>{credits} credit hours</strong> across {enr.length} course(s):
        </p>

        <table>
          <thead><tr><th>Course</th><th>Section</th><th>Schedule</th><th>Credits</th></tr></thead>
          <tbody>
            {enr.map((e) => (
              <tr key={e.enrollmentId}>
                <td><strong>{e.courseCode}</strong> — {e.title}</td>
                <td>{e.sectionCode}</td>
                <td>{e.schedule}</td>
                <td>{e.credits}</td>
              </tr>
            ))}
            {enr.length === 0 && <tr><td colSpan={4} className="muted">No active enrollments.</td></tr>}
          </tbody>
        </table>

        <div className="muted" style={{ fontSize: 11, marginTop: 28, borderTop: "1px solid var(--divider)", paddingTop: 12 }}>
          Generated by myDAUST. For an official sealed letter, contact the Office of the Registrar.
        </div>
      </div>
    </>
  );
}
