/** Canonical country list for the application-form pickers (ISO 3166, English + French labels). Stored value is always the English name. */
export interface CountryOption {
  code: string;
  en: string;
  fr: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: "AF", en: "Afghanistan", fr: "Afghanistan" },
  { code: "AL", en: "Albania", fr: "Albanie" },
  { code: "DZ", en: "Algeria", fr: "Algérie" },
  { code: "AD", en: "Andorra", fr: "Andorre" },
  { code: "AO", en: "Angola", fr: "Angola" },
  { code: "AG", en: "Antigua and Barbuda", fr: "Antigua-et-Barbuda" },
  { code: "AR", en: "Argentina", fr: "Argentine" },
  { code: "AM", en: "Armenia", fr: "Arménie" },
  { code: "AU", en: "Australia", fr: "Australie" },
  { code: "AT", en: "Austria", fr: "Autriche" },
  { code: "AZ", en: "Azerbaijan", fr: "Azerbaïdjan" },
  { code: "BS", en: "Bahamas", fr: "Bahamas" },
  { code: "BH", en: "Bahrain", fr: "Bahreïn" },
  { code: "BD", en: "Bangladesh", fr: "Bangladesh" },
  { code: "BB", en: "Barbados", fr: "Barbade" },
  { code: "BY", en: "Belarus", fr: "Biélorussie" },
  { code: "BE", en: "Belgium", fr: "Belgique" },
  { code: "BZ", en: "Belize", fr: "Belize" },
  { code: "BJ", en: "Benin", fr: "Bénin" },
  { code: "BT", en: "Bhutan", fr: "Bhoutan" },
  { code: "BO", en: "Bolivia", fr: "Bolivie" },
  { code: "BA", en: "Bosnia and Herzegovina", fr: "Bosnie-Herzégovine" },
  { code: "BW", en: "Botswana", fr: "Botswana" },
  { code: "BR", en: "Brazil", fr: "Brésil" },
  { code: "BN", en: "Brunei", fr: "Brunei" },
  { code: "BG", en: "Bulgaria", fr: "Bulgarie" },
  { code: "BF", en: "Burkina Faso", fr: "Burkina Faso" },
  { code: "BI", en: "Burundi", fr: "Burundi" },
  { code: "CV", en: "Cabo Verde", fr: "Cap-Vert" },
  { code: "KH", en: "Cambodia", fr: "Cambodge" },
  { code: "CM", en: "Cameroon", fr: "Cameroun" },
  { code: "CA", en: "Canada", fr: "Canada" },
  { code: "CF", en: "Central African Republic", fr: "République centrafricaine" },
  { code: "TD", en: "Chad", fr: "Tchad" },
  { code: "CL", en: "Chile", fr: "Chili" },
  { code: "CN", en: "China", fr: "Chine" },
  { code: "CO", en: "Colombia", fr: "Colombie" },
  { code: "KM", en: "Comoros", fr: "Comores" },
  { code: "CG", en: "Congo (Republic)", fr: "Congo (République)" },
  { code: "CD", en: "Congo (DRC)", fr: "Congo (RDC)" },
  { code: "CR", en: "Costa Rica", fr: "Costa Rica" },
  { code: "CI", en: "Côte d'Ivoire", fr: "Côte d'Ivoire" },
  { code: "HR", en: "Croatia", fr: "Croatie" },
  { code: "CU", en: "Cuba", fr: "Cuba" },
  { code: "CY", en: "Cyprus", fr: "Chypre" },
  { code: "CZ", en: "Czechia", fr: "Tchéquie" },
  { code: "DK", en: "Denmark", fr: "Danemark" },
  { code: "DJ", en: "Djibouti", fr: "Djibouti" },
  { code: "DM", en: "Dominica", fr: "Dominique" },
  { code: "DO", en: "Dominican Republic", fr: "République dominicaine" },
  { code: "EC", en: "Ecuador", fr: "Équateur" },
  { code: "EG", en: "Egypt", fr: "Égypte" },
  { code: "SV", en: "El Salvador", fr: "Salvador" },
  { code: "GQ", en: "Equatorial Guinea", fr: "Guinée équatoriale" },
  { code: "ER", en: "Eritrea", fr: "Érythrée" },
  { code: "EE", en: "Estonia", fr: "Estonie" },
  { code: "SZ", en: "Eswatini", fr: "Eswatini" },
  { code: "ET", en: "Ethiopia", fr: "Éthiopie" },
  { code: "FJ", en: "Fiji", fr: "Fidji" },
  { code: "FI", en: "Finland", fr: "Finlande" },
  { code: "FR", en: "France", fr: "France" },
  { code: "GA", en: "Gabon", fr: "Gabon" },
  { code: "GM", en: "Gambia", fr: "Gambie" },
  { code: "GE", en: "Georgia", fr: "Géorgie" },
  { code: "DE", en: "Germany", fr: "Allemagne" },
  { code: "GH", en: "Ghana", fr: "Ghana" },
  { code: "GR", en: "Greece", fr: "Grèce" },
  { code: "GD", en: "Grenada", fr: "Grenade" },
  { code: "GT", en: "Guatemala", fr: "Guatemala" },
  { code: "GN", en: "Guinea", fr: "Guinée" },
  { code: "GW", en: "Guinea-Bissau", fr: "Guinée-Bissau" },
  { code: "GY", en: "Guyana", fr: "Guyana" },
  { code: "HT", en: "Haiti", fr: "Haïti" },
  { code: "HN", en: "Honduras", fr: "Honduras" },
  { code: "HU", en: "Hungary", fr: "Hongrie" },
  { code: "IS", en: "Iceland", fr: "Islande" },
  { code: "IN", en: "India", fr: "Inde" },
  { code: "ID", en: "Indonesia", fr: "Indonésie" },
  { code: "IR", en: "Iran", fr: "Iran" },
  { code: "IQ", en: "Iraq", fr: "Irak" },
  { code: "IE", en: "Ireland", fr: "Irlande" },
  { code: "IL", en: "Israel", fr: "Israël" },
  { code: "IT", en: "Italy", fr: "Italie" },
  { code: "JM", en: "Jamaica", fr: "Jamaïque" },
  { code: "JP", en: "Japan", fr: "Japon" },
  { code: "JO", en: "Jordan", fr: "Jordanie" },
  { code: "KZ", en: "Kazakhstan", fr: "Kazakhstan" },
  { code: "KE", en: "Kenya", fr: "Kenya" },
  { code: "KI", en: "Kiribati", fr: "Kiribati" },
  { code: "KP", en: "Korea (North)", fr: "Corée (Nord)" },
  { code: "KR", en: "Korea (South)", fr: "Corée (Sud)" },
  { code: "KW", en: "Kuwait", fr: "Koweït" },
  { code: "KG", en: "Kyrgyzstan", fr: "Kirghizistan" },
  { code: "LA", en: "Laos", fr: "Laos" },
  { code: "LV", en: "Latvia", fr: "Lettonie" },
  { code: "LB", en: "Lebanon", fr: "Liban" },
  { code: "LS", en: "Lesotho", fr: "Lesotho" },
  { code: "LR", en: "Liberia", fr: "Libéria" },
  { code: "LY", en: "Libya", fr: "Libye" },
  { code: "LI", en: "Liechtenstein", fr: "Liechtenstein" },
  { code: "LT", en: "Lithuania", fr: "Lituanie" },
  { code: "LU", en: "Luxembourg", fr: "Luxembourg" },
  { code: "MG", en: "Madagascar", fr: "Madagascar" },
  { code: "MW", en: "Malawi", fr: "Malawi" },
  { code: "MY", en: "Malaysia", fr: "Malaisie" },
  { code: "MV", en: "Maldives", fr: "Maldives" },
  { code: "ML", en: "Mali", fr: "Mali" },
  { code: "MT", en: "Malta", fr: "Malte" },
  { code: "MH", en: "Marshall Islands", fr: "Îles Marshall" },
  { code: "MR", en: "Mauritania", fr: "Mauritanie" },
  { code: "MU", en: "Mauritius", fr: "Maurice" },
  { code: "MX", en: "Mexico", fr: "Mexique" },
  { code: "FM", en: "Micronesia", fr: "Micronésie" },
  { code: "MD", en: "Moldova", fr: "Moldavie" },
  { code: "MC", en: "Monaco", fr: "Monaco" },
  { code: "MN", en: "Mongolia", fr: "Mongolie" },
  { code: "ME", en: "Montenegro", fr: "Monténégro" },
  { code: "MA", en: "Morocco", fr: "Maroc" },
  { code: "MZ", en: "Mozambique", fr: "Mozambique" },
  { code: "MM", en: "Myanmar", fr: "Myanmar" },
  { code: "NA", en: "Namibia", fr: "Namibie" },
  { code: "NR", en: "Nauru", fr: "Nauru" },
  { code: "NP", en: "Nepal", fr: "Népal" },
  { code: "NL", en: "Netherlands", fr: "Pays-Bas" },
  { code: "NZ", en: "New Zealand", fr: "Nouvelle-Zélande" },
  { code: "NI", en: "Nicaragua", fr: "Nicaragua" },
  { code: "NE", en: "Niger", fr: "Niger" },
  { code: "NG", en: "Nigeria", fr: "Nigéria" },
  { code: "MK", en: "North Macedonia", fr: "Macédoine du Nord" },
  { code: "NO", en: "Norway", fr: "Norvège" },
  { code: "OM", en: "Oman", fr: "Oman" },
  { code: "PK", en: "Pakistan", fr: "Pakistan" },
  { code: "PW", en: "Palau", fr: "Palaos" },
  { code: "PS", en: "Palestine", fr: "Palestine" },
  { code: "PA", en: "Panama", fr: "Panama" },
  { code: "PG", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", en: "Paraguay", fr: "Paraguay" },
  { code: "PE", en: "Peru", fr: "Pérou" },
  { code: "PH", en: "Philippines", fr: "Philippines" },
  { code: "PL", en: "Poland", fr: "Pologne" },
  { code: "PT", en: "Portugal", fr: "Portugal" },
  { code: "QA", en: "Qatar", fr: "Qatar" },
  { code: "RO", en: "Romania", fr: "Roumanie" },
  { code: "RU", en: "Russia", fr: "Russie" },
  { code: "RW", en: "Rwanda", fr: "Rwanda" },
  { code: "KN", en: "Saint Kitts and Nevis", fr: "Saint-Christophe-et-Niévès" },
  { code: "LC", en: "Saint Lucia", fr: "Sainte-Lucie" },
  { code: "VC", en: "Saint Vincent and the Grenadines", fr: "Saint-Vincent-et-les-Grenadines" },
  { code: "WS", en: "Samoa", fr: "Samoa" },
  { code: "SM", en: "San Marino", fr: "Saint-Marin" },
  { code: "ST", en: "Sao Tome and Principe", fr: "Sao Tomé-et-Principe" },
  { code: "SA", en: "Saudi Arabia", fr: "Arabie saoudite" },
  { code: "SN", en: "Senegal", fr: "Sénégal" },
  { code: "RS", en: "Serbia", fr: "Serbie" },
  { code: "SC", en: "Seychelles", fr: "Seychelles" },
  { code: "SL", en: "Sierra Leone", fr: "Sierra Leone" },
  { code: "SG", en: "Singapore", fr: "Singapour" },
  { code: "SK", en: "Slovakia", fr: "Slovaquie" },
  { code: "SI", en: "Slovenia", fr: "Slovénie" },
  { code: "SB", en: "Solomon Islands", fr: "Îles Salomon" },
  { code: "SO", en: "Somalia", fr: "Somalie" },
  { code: "ZA", en: "South Africa", fr: "Afrique du Sud" },
  { code: "SS", en: "South Sudan", fr: "Soudan du Sud" },
  { code: "ES", en: "Spain", fr: "Espagne" },
  { code: "LK", en: "Sri Lanka", fr: "Sri Lanka" },
  { code: "SD", en: "Sudan", fr: "Soudan" },
  { code: "SR", en: "Suriname", fr: "Suriname" },
  { code: "SE", en: "Sweden", fr: "Suède" },
  { code: "CH", en: "Switzerland", fr: "Suisse" },
  { code: "SY", en: "Syria", fr: "Syrie" },
  { code: "TJ", en: "Tajikistan", fr: "Tadjikistan" },
  { code: "TZ", en: "Tanzania", fr: "Tanzanie" },
  { code: "TH", en: "Thailand", fr: "Thaïlande" },
  { code: "TL", en: "Timor-Leste", fr: "Timor oriental" },
  { code: "TG", en: "Togo", fr: "Togo" },
  { code: "TO", en: "Tonga", fr: "Tonga" },
  { code: "TT", en: "Trinidad and Tobago", fr: "Trinité-et-Tobago" },
  { code: "TN", en: "Tunisia", fr: "Tunisie" },
  { code: "TR", en: "Turkey", fr: "Turquie" },
  { code: "TM", en: "Turkmenistan", fr: "Turkménistan" },
  { code: "TV", en: "Tuvalu", fr: "Tuvalu" },
  { code: "UG", en: "Uganda", fr: "Ouganda" },
  { code: "UA", en: "Ukraine", fr: "Ukraine" },
  { code: "AE", en: "United Arab Emirates", fr: "Émirats arabes unis" },
  { code: "GB", en: "United Kingdom", fr: "Royaume-Uni" },
  { code: "US", en: "United States", fr: "États-Unis" },
  { code: "UY", en: "Uruguay", fr: "Uruguay" },
  { code: "UZ", en: "Uzbekistan", fr: "Ouzbékistan" },
  { code: "VU", en: "Vanuatu", fr: "Vanuatu" },
  { code: "VA", en: "Vatican City", fr: "Vatican" },
  { code: "VE", en: "Venezuela", fr: "Venezuela" },
  { code: "VN", en: "Vietnam", fr: "Viêt Nam" },
  { code: "YE", en: "Yemen", fr: "Yémen" },
  { code: "ZM", en: "Zambia", fr: "Zambie" },
  { code: "ZW", en: "Zimbabwe", fr: "Zimbabwe" },
];
