"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { type GradeRow, type Me, type MySummary, getMe, getMyGrades, getMySummary } from "@/lib/api";

export default function TranscriptPage() {
  const [me, setMe] = useState<Me | null>(null);
  const [grades, setGrades] = useState<GradeRow[]>([]);
  const [summary, setSummary] = useState<MySummary | null>(null);

  useEffect(() => {
    Promise.all([getMe(), getMyGrades(), getMySummary()])
      .then(([m, g, s]) => { setMe(m); setGrades(g); setSummary(s); })
      .catch(() => {});
  }, []);

  return (
    <>
      <style>{`@media print { .no-print { display: none !important; } .doc-sheet { box-shadow: none !important; border: none !important; margin: 0 !important; } body { background: #fff !important; } }`}</style>

      <div className="no-print" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
        <Link href="/student/documents" className="eyebrow">← Documents</Link>
        <span style={{ flex: 1 }} />
        <button className="primary" onClick={() => window.print()}>Print / Save as PDF</button>
      </div>

      <div className="doc-sheet card" style={{ maxWidth: 820, margin: "0 auto", padding: 40 }}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "2px solid var(--daust-navy)", paddingBottom: 16 }}>
          <div>
            <div style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 26, color: "var(--daust-navy)", letterSpacing: ".04em" }}>DAUST</div>
            <div className="muted" style={{ fontSize: 12 }}>Dakar American University of Science & Technology</div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 18 }}>Official Transcript</div>
            <div className="muted" style={{ fontSize: 12 }}>Issued {new Date().toLocaleDateString()}</div>
          </div>
        </div>

        <div style={{ display: "flex", gap: 40, margin: "20px 0" }}>
          <div>
            <div className="muted" style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: ".06em" }}>Student</div>
            <div style={{ fontWeight: 600 }}>{me?.name ?? "—"}</div>
            <div className="muted" style={{ fontSize: 13 }}>{me?.email}</div>
          </div>
          <div>
            <div className="muted" style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: ".06em" }}>Cumulative GPA</div>
            <div style={{ fontWeight: 700, fontFamily: "var(--font-display)", fontSize: 20 }}>{summary?.gpa?.toFixed(2) ?? "—"}</div>
          </div>
          <div>
            <div className="muted" style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: ".06em" }}>Credits earned</div>
            <div style={{ fontWeight: 700, fontFamily: "var(--font-display)", fontSize: 20 }}>{summary?.completedCredits ?? 0}</div>
          </div>
        </div>

        <table>
          <thead><tr><th>Course</th><th>Term</th><th>Credits</th><th>Grade</th><th>Points</th></tr></thead>
          <tbody>
            {grades.map((g, i) => (
              <tr key={i}>
                <td><strong>{g.courseCode}</strong> — {g.title}</td>
                <td>{g.term}</td>
                <td>{g.credits}</td>
                <td>{g.grade}</td>
                <td>{g.points?.toFixed(1) ?? "—"}</td>
              </tr>
            ))}
            {grades.length === 0 && <tr><td colSpan={5} className="muted">No completed courses on record.</td></tr>}
          </tbody>
        </table>

        <div className="muted" style={{ fontSize: 11, marginTop: 28, borderTop: "1px solid var(--divider)", paddingTop: 12 }}>
          This document is generated by myDAUST. An official sealed copy is available from the Office of the Registrar.
        </div>
      </div>
    </>
  );
}
